[package]
name = "indracore-runtime-parachains"
version = "0.8.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
log = "0.4.11"
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.118", features = [ "derive" ], optional = true }
derive_more = "0.99.11"

inherents = { package = "sp-inherents", path = "../../substrate/primitives/inherents", default-features = false }
sp-api = { path = "../../substrate/primitives/api", default-features = false }
sp-std = { path = "../../substrate/primitives/std", default-features = false }
sp-io = { path = "../../substrate/primitives/io", default-features = false }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
sp-session = { path = "../../substrate/primitives/session", default-features = false }
sp-staking = { path = "../../substrate/primitives/staking", default-features = false }
sp-core = { path = "../../substrate/primitives/core", default-features = false }
sp-keystore = { path = "../../substrate/primitives/keystore", optional = true }

frame-support = { path = "../../substrate/frame/support", default-features = false }
frame-benchmarking = { path = "../../substrate/frame/benchmarking", default-features = false, optional = true }
frame-system = { path = "../../substrate/frame/system", default-features = false }
pallet-authority-discovery = { path = "../../substrate/frame/authority-discovery", default-features = false }
pallet-authorship = { path = "../../substrate/frame/authorship", default-features = false }
pallet-balances = { path = "../../substrate/frame/balances", default-features = false }
pallet-session = { path = "../../substrate/frame/session", default-features = false }
pallet-staking = { path = "../../substrate/frame/staking", default-features = false }
pallet-timestamp = { path = "../../substrate/frame/timestamp", default-features = false }
pallet-vesting = { path = "../../substrate/frame/vesting", default-features = false }
pallet-offences = { path = "../../substrate/frame/offences", default-features = false }


xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
primitives = { package = "indracore-primitives", path = "../../primitives", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false, optional = true }

rand = { version = "0.7.3", default-features = false }
rand_chacha = { version = "0.2.2", default-features = false }

[dev-dependencies]
futures = "0.3.8"
hex-literal = "0.3.1"
serde_json = "1.0.61"
libsecp256k1 = "0.3.5"

keyring = { package = "sp-keyring", path = "../../substrate/primitives/keyring" }
sp-trie = { path = "../../substrate/primitives/trie" }
sp-application-crypto = { path = "../../substrate/primitives/application-crypto" }
sp-version = { path = "../../substrate/primitives/version", default-features = false }
sc-keystore = { path = "../../substrate/client/keystore"}

pallet-babe = { path = "../../substrate/frame/babe" }
pallet-randomness-collective-flip = { path = "../../substrate/frame/randomness-collective-flip" }
pallet-staking-reward-curve = { path = "../../substrate/frame/staking/reward-curve" }
pallet-treasury = { path = "../../substrate/frame/treasury" }




[features]
default = ["std"]
no_std = []
std = [
	"bitvec/std",
	"parity-scale-codec/std",
	"rustc-hex/std",
	"serde",
	"primitives/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-keystore",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-staking/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"xcm/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"libsecp256k1/hmac",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
