[package]
name = "indracore-network-bridge"
version = "0.1.0"
authors = ["Selendra <nath@selendra.org>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
indracore-primitives = { path = "../../../primitives" }
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
sc-authority-discovery = {path = "../../../substrate/client/authority-discovery" }
sc-network = {path = "../../../substrate/client/network" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-network-protocol = { path = "../protocol" }

[dev-dependencies]
assert_matches = "1.4.0"
parking_lot = "0.11.1"
indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = {path = "../../../substrate/primitives/core" }
sp-keyring = {path = "../../../substrate/primitives/keyring" }
