[package]
name = "indracore-network-bridge"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
indracore-primitives = { path = "../../../primitives" }
parity-scale-codec = { version = "1.3.6", default-features = false, features = ["derive"] }
sc-authority-discovery = { git = "https://github.com/laynath242/substrate", branch = "master" }
sc-network = { git = "https://github.com/laynath242/substrate", branch = "master" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-network-protocol = { path = "../protocol" }

[dev-dependencies]
assert_matches = "1.4.0"
parking_lot = "0.11.1"
indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/laynath242/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/laynath242/substrate", branch = "master" }
