[package]
authors = ['Selendra <nath@selendra.org>']
edition = '2018'
name = 'node-indracore-runtime'
version = "2.0.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { path = "../../substrate/utils/wasm-builder" }

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
hex-literal = { optional = true, version = '0.3.1' }
static_assertions = "1.1.0"
serde = { features = ['derive'], optional = true, version = '1.0.101' }
smallvec = "1.5.1"

# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, path = "../../substrate/frame/benchmarking" }
frame-system-benchmarking = { default-features = false, optional = true, path = "../../substrate/frame/system/benchmarking" }
pallet-session-benchmarking = { path = "../../substrate/frame/session/benchmarking", default-features = false, optional = true }
pallet-offences-benchmarking = { path = "../../substrate/frame/offences/benchmarking", default-features = false, optional = true }

frame-executive = { default-features = false, path = "../../substrate/frame/executive" }
frame-support = { default-features = false, path = "../../substrate/frame/support" }
frame-system = { default-features = false, path = "../../substrate/frame/system" }
frame-system-rpc-runtime-api = { default-features = false, path = "../../substrate/frame/system/rpc/runtime-api" }

pallet-balances = { default-features = false, path = "../../substrate/frame/balances" }
pallet-grandpa = { default-features = false, path = "../../substrate/frame/grandpa" }
pallet-randomness-collective-flip = { default-features = false, path = "../../substrate/frame/randomness-collective-flip" }
pallet-sudo = { default-features = false, path = "../../substrate/frame/sudo" }
pallet-timestamp = { default-features = false, path = "../../substrate/frame/timestamp" }
pallet-transaction-payment = { default-features = false, path = "../../substrate/frame/transaction-payment" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, path = "../../substrate/frame/transaction-payment/rpc/runtime-api" }
pallet-scheduler = { default-features = false, path = "../../substrate/frame/scheduler" }
pallet-collective = { default-features = false, path = "../../substrate/frame/collective" }
pallet-membership = { default-features = false, path = "../../substrate/frame/membership" }
pallet-elections-phragmen = { default-features = false, path = "../../substrate/frame/elections-phragmen" }
pallet-democracy = { default-features = false, path = "../../substrate/frame/democracy" }
pallet-treasury = { default-features = false, path = "../../substrate/frame/treasury" }
pallet-bounties = { default-features = false, path = "../../substrate/frame/bounties" }
pallet-tips = { default-features = false, path = "../../substrate/frame/tips" }
pallet-session = { path = "../../substrate/frame/session", default-features = false, features = ["historical"] }
pallet-staking = { default-features = false, path = "../../substrate/frame/staking" }
pallet-staking-reward-curve = { path = "../../substrate/frame/staking/reward-curve" }
pallet-authorship = { path = "../../substrate/frame/authorship", default-features = false }
pallet-im-online = { path = "../../substrate/frame/im-online", default-features = false }
pallet-utility = { path = "../../substrate/frame/utility", default-features = false }
pallet-offences = { path = "../../substrate/frame/offences", default-features = false }
pallet-authority-discovery = { path = "../../substrate/frame/authority-discovery", default-features = false }
pallet-indices = { path = "../../substrate/frame/indices", default-features = false }
pallet-identity = { path = "../../substrate/frame/identity", default-features = false }
pallet-vesting = { path = "../../substrate/frame/vesting", default-features = false }
pallet-multisig = { path = "../../substrate/frame/multisig", default-features = false }
pallet-proxy = { path = "../../substrate/frame/proxy", default-features = false }
pallet-babe = {  path = "../../substrate/frame/babe", default-features = false }

sp-api = { default-features = false, path = "../../substrate/primitives/api" }
sp-block-builder = { default-features = false, path = "../../substrate/primitives/block-builder" }
sp-core = { default-features = false, path = "../../substrate/primitives/core" }
sp-inherents = { default-features = false, path = "../../substrate/primitives/inherents" }
sp-offchain = { default-features = false, path = "../../substrate/primitives/offchain" }
sp-runtime = { default-features = false, path = "../../substrate/primitives/runtime" }
sp-session = { default-features = false, path = "../../substrate/primitives/session" }
sp-std = { default-features = false, path = "../../substrate/primitives/std" }
sp-transaction-pool = { default-features = false, path = "../../substrate/primitives/transaction-pool" }
sp-version = { default-features = false, path = "../../substrate/primitives/version" }
sp-staking = { default-features = false, path = "../../substrate/primitives/staking" }
sp-authority-discovery = { path = "../../substrate/primitives/authority-discovery", default-features = false }
sp-consensus-babe = { path = "../../substrate/primitives/consensus/babe",  default-features = false }

primitives = { package = 'indracore-primitives', path = "../../primitives", default-features = false }
common = { package = "runtime-common", path = "../common", default-features = false }
runtime-parachains = { package = "indracore-runtime-parachains", path = "../parachains", default-features = false }
indracore-parachain = { path = "../../parachain", default-features = false }
xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
xcm-builder = { package = "xcm-builder", path = "../../xcm/xcm-builder", default-features = false }


[features]
default = ['std']
std = [
    'codec/std',
    'serde',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-balances/std',
    'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'pallet-scheduler/std',
    'pallet-collective/std',
    'pallet-membership/std',
    'pallet-elections-phragmen/std',
    'pallet-democracy/std',
    'pallet-treasury/std',
    'pallet-session/std',
    'pallet-staking/std',
    'sp-staking/std',
    "pallet-authorship/std",
    "pallet-im-online/std",
    "pallet-offences/std",
    "pallet-utility/std",
    "pallet-babe/std",
    'pallet-authority-discovery/std',
    'sp-consensus-babe/std',
    'sp-authority-discovery/std',
    'pallet-indices/std',
    'pallet-identity/std',
    'pallet-vesting/std',
    'pallet-multisig/std',
    'pallet-proxy/std',
    "pallet-bounties/std",
    "pallet-tips/std",
    "xcm/std",
	"xcm-executor/std",
	"xcm-builder/std",
    "runtime-parachains/std",
    "indracore-parachain/std",
]

runtime-benchmarks = [
    'hex-literal',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
    'pallet-scheduler/runtime-benchmarks',
    'pallet-collective/runtime-benchmarks',
    'pallet-elections-phragmen/runtime-benchmarks',
    'pallet-democracy/runtime-benchmarks',
    'pallet-treasury/runtime-benchmarks',
    'pallet-session-benchmarking',
    "pallet-staking/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-offences-benchmarking",
    "pallet-utility/runtime-benchmarks",  
    "pallet-babe/runtime-benchmarks",
    "pallet-grandpa/runtime-benchmarks",
    'pallet-indices/runtime-benchmarks',
    'pallet-identity/runtime-benchmarks',
    'pallet-vesting/runtime-benchmarks',
    'pallet-multisig/std',
    'pallet-proxy/std',
]
