[package]
authors = ['Selendra <nath@selendra.org>']
edition = '2018'
name = 'core-primitives'
version = '2.0.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
serde = { features = ['derive'], optional = true, version = '1.0.101' }

frame-system = { version = "2.0.0", default-features = false }
sp-application-crypto = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false}

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-system/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
    "serde"
]