[package]
authors = ['Selendra <nath@selendra.org>']
edition = '2018'
name = 'indracore-core-primitives'
version = '2.0.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-core = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false}
sp-runtime = { version = "2.0.0", default-features = false}

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
]