[package]
name = "xelendra-runtime"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
serde = { version = "1.0.118", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
smallvec = "1.5.1"

tx-pool = { package = "sp-transaction-pool", path = "../../substrate/primitives/transaction-pool", default-features = false }
sp-block-builder = { path = "../../substrate/primitives/block-builder", default-features = false }
inherents = { package = "sp-inherents", path = "../../substrate/primitives/inherents", default-features = false }
babe-primitives = { package = "sp-consensus-babe", path = "../../substrate/primitives/consensus/babe", default-features = false }
sp-offchain = { path = "../../substrate/primitives/offchain", default-features = false }
sp-api = { path = "../../substrate/primitives/api", default-features = false }
sp-io = { path = "../../substrate/primitives/io", default-features = false }
sp-std = { package = "sp-std", path = "../../substrate/primitives/std", default-features = false }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
sp-session = { path = "../../substrate/primitives/session", default-features = false }
sp-staking = { path = "../../substrate/primitives/staking", default-features = false }
sp-core = { path = "../../substrate/primitives/core", default-features = false }
sp-version = { path = "../../substrate/primitives/version", default-features = false }
sp-authority-discovery = { path = "../../substrate/primitives/authority-discovery", default-features = false }


frame-system = { path = "../../substrate/frame/system", default-features = false }
frame-system-rpc-runtime-api = { path = "../../substrate/frame/system/rpc/runtime-api", default-features = false }
frame-support = { path = "../../substrate/frame/support", default-features = false }
frame-executive = { path = "../../substrate/frame/executive", default-features = false }
pallet-authority-discovery = { path = "../../substrate/frame/authority-discovery", default-features = false }
pallet-authorship = { path = "../../substrate/frame/authorship", default-features = false }
pallet-babe = { path = "../../substrate/frame/babe", default-features = false }
pallet-sudo = { path = "../../substrate/frame/sudo", default-features = false }
pallet-balances = { path = "../../substrate/frame/balances", default-features = false }
pallet-session = { path = "../../substrate/frame/session", default-features = false }
pallet-im-online = { path = "../../substrate/frame/im-online", default-features = false }
pallet-indices = { path = "../../substrate/frame/indices", default-features = false }
pallet-transaction-payment = { path = "../../substrate/frame/transaction-payment", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { path = "../../substrate/frame/transaction-payment/rpc/runtime-api", default-features = false }
pallet-staking = { path = "../../substrate/frame/staking", default-features = false }
pallet-staking-reward-curve = { package = "pallet-staking-reward-curve", path = "../../substrate/frame/staking/reward-curve" }
pallet-grandpa = { path = "../../substrate/frame/grandpa", default-features = false }
pallet-timestamp = { path = "../../substrate/frame/timestamp", default-features = false }
pallet-offences = { path = "../../substrate/frame/offences", default-features = false }
pallet-contracts = { path = "../../substrate/frame/contracts", default_features = false }
pallet-contracts-primitives = { path = "../../substrate/frame/contracts/common", default_features = false }
pallet-contracts-rpc-runtime-api = { path = "../../substrate/frame/contracts/rpc/runtime-api", default_features = false }
pallet-randomness-collective-flip = { path = "../../substrate/frame/randomness-collective-flip", default-features = false }

runtime-common = { package = "indracore-runtime-common", path = "../common", default-features = false }
primitives = { package = "indracore-primitives", path = "../../primitives", default-features = false }
indracore-parachain = { path = "../../parachain", default-features = false }
runtime-parachains = { package = "indracore-runtime-parachains", path = "../parachains", default-features = false }

xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
xcm-builder = { package = "xcm-builder", path = "../../xcm/xcm-builder", default-features = false }

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = ["std"]
no_std = []
std = [
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"babe-primitives/std",
	"pallet-balances/std",
	"parity-scale-codec/std",
	"frame-executive/std",
	"pallet-grandpa/std",
	"pallet-sudo/std",
	"pallet-indices/std",
	"pallet-im-online/std",
	"inherents/std",
	"frame-support/std",
	"indracore-parachain/std",
	"primitives/std",
	"runtime-common/std",
	"runtime-parachains/std",
	"pallet-session/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"pallet-staking/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"sp-block-builder/std",
	"tx-pool/std",
	"sp-version/std",
	"serde_derive",
	"serde/std",
	"xcm/std",
	"xcm-executor/std",
	"xcm-builder/std",
	'pallet-contracts/std',
    'pallet-contracts-primitives/std',
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-randomness-collective-flip/std",
]
# When enabled, the runtime api will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime api exported functions
# in WASM.
disable-runtime-api = []
