[package]
name = "xcm-builder"
version = "0.8.22"
description = "Tools & types for building with XCM and its executor."
authors = ["Selendra <info@selendra.org>"]
edition = "2018"


[dependencies]
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

# Indracore dependencies
indracore-parachain = { path = "../../parachain", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"xcm/std",
	"xcm-executor/std",
	"sp-std/std",
	"sp-arithmetic/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-support/std",
	"indracore-parachain/std",
]
