[package]
authors = ["Selendra <nath@selendra.org>"]
edition = "2018"
name = "xcm-builder"
description = "Tools & types for building with XCM and its executor."
version = "0.8.22"

[dependencies]
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }
sp-std = { path = "../../substrate/primitives/std", default-features = false }
sp-arithmetic = { path = "../../substrate/primitives/arithmetic", default-features = false }
sp-io = { path = "../../substrate/primitives/io", default-features = false }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
frame-support = { path = "../../substrate/frame/support", default-features = false }

# Indracore dependencies
indracore-parachain = { path = "../../parachain", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"xcm/std",
	"xcm-executor/std",
	"sp-std/std",
	"sp-arithmetic/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-support/std",
	"indracore-parachain/std",
]
