[package]
name = "indracore-runtime-common"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
log = { version = "0.4.11", optional = true }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.118", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"

sp-api = { path = "../../substrate/primitives/api", default-features = false }
sp-inherents = { package = "sp-inherents", path = "../../substrate/primitives/inherents", default-features = false }
sp-std = { package = "sp-std", path = "../../substrate/primitives/std", default-features = false }
sp-io = { path = "../../substrate/primitives/io", default-features = false }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
sp-session = { path = "../../substrate/primitives/session", default-features = false }
sp-staking = { path = "../../substrate/primitives/staking", default-features = false }
sp-core = { path = "../../substrate/primitives/core", default-features = false }

frame-benchmarking = { path = "../../substrate/frame/benchmarking", default-features = false, optional = true }
frame-support = { path = "../../substrate/frame/support", default-features = false }
frame-system = {path = "../../substrate/frame/system", default-features = false }
pallet-authorship = { path = "../../substrate/frame/authorship", default-features = false }
pallet-balances = { path = "../../substrate/frame/balances", default-features = false }
pallet-session = { path = "../../substrate/frame/session", default-features = false }
pallet-staking = { path = "../../substrate/frame/staking", default-features = false }
pallet-timestamp = { path = "../../substrate/frame/timestamp", default-features = false }
pallet-vesting = { path = "../../substrate/frame/vesting", default-features = false }
pallet-offences = { path = "../../substrate/frame/offences", default-features = false }
pallet-transaction-payment = { path = "../../substrate/frame/transaction-payment", default-features = false }
pallet-treasury = { path = "../../substrate/frame/treasury", default-features = false }


primitives = { package = "indracore-primitives", path = "../../primitives", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false, optional = true }
runtime-parachains = { package = "indracore-runtime-parachains", path = "../parachains", default-features = false }

xcm = { path = "../../xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
trie-db = "0.22.1"
serde_json = "1.0.61"
libsecp256k1 = "0.3.5"

pallet-randomness-collective-flip = { path = "../../substrate/frame/randomness-collective-flip" }
pallet-staking-reward-curve = { path = "../../substrate/frame/staking/reward-curve" }
pallet-treasury = { path = "../../substrate/frame/treasury" }
pallet-babe = { path = "../../substrate/frame/babe" }
sp-application-crypto = { path = "../../substrate/primitives/application-crypto" }
keyring = { package = "sp-keyring", path = "../../substrate/primitives/keyring" }
sp-trie = { path = "../../substrate/primitives/trie" }


[features]
default = ["std"]
no_std = []
std = [
	"bitvec/std",
	"parity-scale-codec/std",
	"log",
	"rustc-hex/std",
	"serde_derive",
	"serde/std",
	"primitives/std",
	"sp-inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-staking/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"pallet-transaction-payment/std",
	"runtime-parachains/std",
	"xcm/std",
]
runtime-benchmarks = [
	"libsecp256k1/hmac",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
