[package]
name = "runtime-common"
version = "0.8.27"
authors = ["Selendra <nath@selendra.org>"]
edition = "2018"

[dependencies]
sp-runtime = { default-features = false, path = "../../substrate/primitives/runtime" }
frame-support = { default-features = false, path = "../../substrate/frame/support" }
pallet-transaction-payment = { default-features = false, path = "../../substrate/frame/transaction-payment" }
sp-io = { path = "../../substrate/primitives/io", default-features = false }

[features]
default = ['std']
std = [
    "sp-runtime/std",
    "frame-support/std",
    "pallet-transaction-payment/std",
    "sp-io/std",
]