[package]
name = "indracore-node-core-bitfield-signing"
version = "0.1.0"
authors = ["Selendra <nath@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
indracore-primitives = { path = "../../../primitives" }
indracore-node-subsystem = { path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
sp-keystore = { path = "../../../substrate/primitives/keystore" }
wasm-timer = "0.2.5"
thiserror = "1.0.22"
