[package]
name = "indracore-test-runtime"
version = "0.8.27"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
log = { version = "0.4.11", optional = true }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.118", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
smallvec = "1.5.1"

inherents = { package = "sp-inherents", path ="../../substrate/primitives/inherents", default-features = false }
authority-discovery-primitives = { package = "sp-authority-discovery", path ="../../substrate/primitives/authority-discovery", default-features = false }
babe-primitives = { package = "sp-consensus-babe", path ="../../substrate/primitives/consensus/babe", default-features = false }
offchain-primitives = { package = "sp-offchain", path ="../../substrate/primitives/offchain", default-features = false }
tx-pool-api = { package = "sp-transaction-pool", path ="../../substrate/primitives/transaction-pool", default-features = false }
block-builder-api = { package = "sp-block-builder", path ="../../substrate/primitives/block-builder", default-features = false }

sp-api = { path ="../../substrate/primitives/api", default-features = false }
sp-std = { path ="../../substrate/primitives/std", default-features = false }
sp-io = { path ="../../substrate/primitives/io", default-features = false }
sp-runtime = { path ="../../substrate/primitives/runtime", default-features = false }
sp-staking = { path ="../../substrate/primitives/staking", default-features = false }
sp-core = { path ="../../substrate/primitives/core", default-features = false }
sp-session = { path ="../../substrate/primitives/session", default-features = false }
sp-version = { path ="../../substrate/primitives/version", default-features = false }

frame-system = { path ="../../substrate/frame/system", default-features = false }
frame-system-rpc-runtime-api = { path ="../../substrate/frame/system/rpc/runtime-api", default-features = false }
frame-executive = { path ="../../substrate/frame/executive", default-features = false }
frame-support = { path ="../../substrate/frame/support", default-features = false }

pallet-authority-discovery = { path ="../../substrate/frame/authority-discovery", default-features = false }
pallet-authorship = { path ="../../substrate/frame/authorship", default-features = false }
pallet-babe = { path ="../../substrate/frame/babe", default-features = false }
pallet-balances = { path ="../../substrate/frame/balances", default-features = false }
pallet-transaction-payment = { path ="../../substrate/frame/transaction-payment", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { path ="../../substrate/frame/transaction-payment/rpc/runtime-api", default-features = false }
pallet-grandpa = { path ="../../substrate/frame/grandpa", default-features = false }
pallet-indices = { path ="../../substrate/frame/indices", default-features = false }
pallet-nicks = { path ="../../substrate/frame/nicks", default-features = false }
pallet-offences = { path ="../../substrate/frame/offences", default-features = false }
pallet-randomness-collective-flip = { path ="../../substrate/frame/randomness-collective-flip", default-features = false }
pallet-session = { path ="../../substrate/frame/session", default-features = false }
pallet-staking = { path ="../../substrate/frame/staking", default-features = false }
pallet-staking-reward-curve = { path ="../../substrate/frame/staking/reward-curve" }
pallet-timestamp = { path ="../../substrate/frame/timestamp", default-features = false }
pallet-sudo = { path ="../../substrate/frame/sudo", default-features = false }
pallet-vesting = { path ="../../substrate/frame/vesting", default-features = false }

runtime-common = { package = "indracore-runtime-common", path = "../common", default-features = false }
primitives = { package = "indracore-primitives", path = "../../primitives", default-features = false }
indracore-parachain = { path = "../../parachain", default-features = false }
indracore-runtime-parachains = { path = "../parachains", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
libsecp256k1 = "0.3.5"
tiny-keccak = "2.0.2"
keyring = { package = "sp-keyring", path ="../../substrate/primitives/keyring" }
sp-trie = { path ="../../substrate/primitives/trie" }
serde_json = "1.0.60"

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = ["std"]
no_std = []
only-staking = []
std = [
	"authority-discovery-primitives/std",
	"pallet-authority-discovery/std",
	"bitvec/std",
	"primitives/std",
	"rustc-hex/std",
	"parity-scale-codec/std",
	"inherents/std",
	"sp-core/std",
	"indracore-parachain/std",
	"sp-api/std",
	"tx-pool-api/std",
	"block-builder-api/std",
	"offchain-primitives/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"frame-executive/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-nicks/std",
	"pallet-offences/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-staking/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-timestamp/std",
	"sp-version/std",
	"pallet-vesting/std",
	"serde_derive",
	"serde/std",
	"log",
	"pallet-babe/std",
	"babe-primitives/std",
	"sp-session/std",
	"pallet-randomness-collective-flip/std",
	"runtime-common/std",
]
