[package]
name = "indracore-node-subsystem-util"
version = "0.1.0"
authors = ["Selendra <nath@selendra.org>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.8"
futures-timer = "3.0.2"
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
parking_lot = { version = "0.11.1", optional = true }
pin-project = "1.0.2"
streamunordered = "0.5.1"
thiserror = "1.0.22"
tracing = "0.1.22"
tracing-futures = "0.2.4"

indracore-node-primitives = { path = "../primitives" }
indracore-node-subsystem = { path = "../subsystem" }
indracore-primitives = { path = "../../primitives" }

sc-network = { path = "../../substrate/client/network" }
sp-core = { path = "../../substrate/primitives/core"}
sp-application-crypto = { path = "../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../substrate/primitives/keystore" }
substrate-prometheus-endpoint = { path = "../../substrate/utils/prometheus" }

[dev-dependencies]
assert_matches = "1.4.0"
async-trait = "0.1.42"
env_logger = "0.8.2"
futures = { version = "0.3.8", features = ["thread-pool"] }
log = "0.4.11"
parking_lot = "0.11.1"
indracore-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }