[package]
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
name = "xcm-executor"
description = "An abstract and configurable XCM message executor."
version = "0.8.22"

[dependencies]
impl-trait-for-tuples = "0.2.0"
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
sp-std = { path = "../../substrate/primitives/std", default-features = false }
sp-io = { path = "../../substrate/primitives/io", default-features = false }
sp-arithmetic = { path = "../../substrate/primitives/arithmetic", default-features = false }
sp-core = { path = "../../substrate/primitives/core", default-features = false }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
frame-support = { path = "../../substrate/frame/support", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"xcm/std",
	"sp-std/std",
	"sp-io/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
]
