[package]
name = "indracore-collator-protocol"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
thiserror = "1.0.23"


indracore-primitives = { path = "../../../primitives" }
indracore-node-network-protocol = { path = "../../network/protocol" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }

[dev-dependencies]
log = "0.4.11"
env_logger = "0.8.2"
assert_matches = "1.4.0"
smallvec = "1.5.1"
futures-timer = "3.0.2"

sp-core = {path = "../../../substrate/primitives/core", features = ["std"] }
sp-keyring = {path = "../../../substrate/primitives/keyring" }

indracore-subsystem-testhelpers = { package = "indracore-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
