[package]
name = 'xelendra-collator'
version = '0.1.0'
authors = ["Selendra <info@selendra.org>"]
build = 'build.rs'
edition = '2018'

[[bin]]
name = 'xelendra-collator'
path = 'src/main.rs'

[dependencies]
derive_more = '0.15.0'
exit-future = '0.1.4'
futures = { version = "0.3.1", features = ["compat"] }
log = '0.4.8'
parking_lot = '0.9.0'
trie-root = '0.15.2'
codec = { package = 'parity-scale-codec', version = '1.0.0' }
structopt = "0.3.3"
serde = { version = "1.0.101", features = ["derive"] }
hex-literal = "0.2.1"

# Parachain dependencies
parachain-runtime = { package = "xelendra-parachain-runtime", path = "../runtime" }
xelendra-parachain-primitives = { path = "../primitives" }

# Substrate dependencies
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false }
sp-io = { path = "../../substrate/primitives/io" }
sp-core = { path = "../../substrate/primitives/core" }
sp-inherents = { path = "../../substrate/primitives/inherents" }
sp-consensus = { path = "../../substrate/primitives/consensus/common" }
sp-session = { path = "../../substrate/primitives/session" }
sp-timestamp = { path = "../../substrate/primitives/timestamp" }
sp-blockchain = { path = "../../substrate/primitives/blockchain" }
sp-block-builder = { path = "../../substrate/primitives/block-builder" }
sp-trie = { path = "../../substrate/primitives/trie" }
sp-offchain = { path = "../../substrate/primitives/offchain" }
sp-transaction-pool = { path = "../../substrate/primitives/transaction-pool" }

sc-consensus = { path = "../../substrate/client/consensus/common" }
sc-cli = { path = "../../substrate/client/cli" }
sc-client-api = { path = "../../substrate/client/api" }
sc-executor = { path = "../../substrate/client/executor" }
sc-service = { path = "../../substrate/client/service" }
sc-transaction-pool = { path = "../../substrate/client/transaction-pool" }
sc-network = { path = "../../substrate/client/network" }
sc-basic-authorship = { path = "../../substrate/client/basic-authorship" }
sc-finality-grandpa = { path = "../../substrate/client/finality-grandpa" }
sc-chain-spec = { path = "../../substrate/client/chain-spec" }
sc-rpc = { path = "../../substrate/client/rpc" }
sc-tracing = { path = "../../substrate/client/tracing" }



# RPC related dependencies
jsonrpc-core = "15.1.0"

# Cumulus dependencies
cumulus-consensus = { path = "../../cumulus/consensus" }
cumulus-collator = { path = "../../cumulus/collator" }
cumulus-network = { path = "../../cumulus/network" }
cumulus-primitives = { path = "../../cumulus/primitives" }
cumulus-service = { path = "../../cumulus/service" }

# Indracore dependencies
indracore-primitives = { path = "../../primitives" }
indracore-service = { path = "../../node/service" }
indracore-cli = { path = "../../cli" }
indracore-test-service = { path = "../../node/test/service" }
indracore-parachain = { path = "../../parachain" }

[build-dependencies]
substrate-build-script-utils = { path = "../../substrate/utils/build-script-utils" }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"
tokio = { version = "0.2.13", features = ["macros"] }

# Indracore dependencies
indracore-runtime-common = { path = "../../runtime/common" }
indracore-test-runtime = { path = "../../runtime/test-runtime" }
indracore-test-client = { path = "../../node/test/client" }
indracore-test-service = { path = "../../node/test/service" }

# Substrate dependencies
pallet-sudo = { path = "../../substrate/frame/sudo" }
substrate-test-client = { path = "../../substrate/test-utils/client" }
substrate-test-runtime-client = { path = "../../substrate/test-utils/runtime/client" }