[package]
name = "indracore-node-core-av-store"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
futures-timer = "3.0.2"
kvdb = "0.8.0"
kvdb-rocksdb = "0.10.0"
thiserror = "1.0.23"
tracing = "0.1.22"
tracing-futures = "0.2.4"
smallvec = "1.6.1"

parity-scale-codec = { version = "1.3.5", features = ["derive"] }
erasure = { package = "indracore-erasure-coding", path = "../../../erasure-coding" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-overseer = { path = "../../overseer" }
indracore-primitives = { path = "../../../primitives" }

sc-service = { git = "https://github.com/LayNath242/substrate", branch = "master", default-features = false }

[dev-dependencies]
log = "0.4.11"
env_logger = "0.8.2"
assert_matches = "1.4.0"
smallvec = "1.6.1"
kvdb-memorydb = "0.8.0"

sp-core = { git = "https://github.com/LayNath242/substrate", branch = "master" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
