[package]
name = "test-parachain-adder-collator"
version = "0.7.26"
authors = ["Selendra <info@selendra.org>"]
description = "Collator for the adder test parachain"
edition = "2018"

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[dependencies]
parity-scale-codec = { version = "1.3.6", default-features = false, features = ["derive"] }
futures = "0.3.12"
futures-timer = "3.0.2"
log = "0.4.13"
structopt = "0.3.21"

test-parachain-adder = { path = ".." }
indracore-primitives = { path = "../../../../primitives" }
indracore-cli = { path = "../../../../cli" }
indracore-service = { path = "../../../../node/service" }
indracore-node-primitives = { path = "../../../../node/primitives" }
indracore-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }
sc-authority-discovery = { git = "https://github.com/selendra/substrate", branch = "master" }
sc-service = { git = "https://github.com/selendra/substrate", branch = "master" }

[dev-dependencies]
indracore-parachain = { path = "../../.." }
indracore-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { git = "https://github.com/selendra/substrate", branch = "master" }
sc-service = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "master" }

tokio = { version = "0.2", features = ["macros"] }

[features]
real-overseer = [ "indracore-service/real-overseer" ]
