[package]
name = "test-parachain-adder-collator"
version = "0.7.26"
authors = ["Selendra <info@selendra.org>"]
description = "Collator for the adder test parachain"
edition = "2018"

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[dependencies]
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
futures = "0.3.8"
futures-timer = "3.0.2"
log = "0.4.11"
structopt = "0.3.21"

test-parachain-adder = { path = ".." }
indracore-primitives = { path = "../../../../primitives" }
indracore-cli = { path = "../../../../cli" }
indracore-service = { path = "../../../../node/service" }
indracore-node-primitives = { path = "../../../../node/primitives" }
indracore-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { path = "../../../../substrate/client/cli" }
sp-core = { path = "../../../../substrate/primitives/core" }
sc-authority-discovery = { path = "../../../../substrate/client/authority-discovery" }
sc-service = { path = "../../../../substrate/client/service" }

[dev-dependencies]
indracore-parachain = { path = "../../../../parachain" }
indracore-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { path = "../../../../substrate/test-utils" }
sc-service = { path = "../../../../substrate/client/service" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }

tokio = { version = "0.2", features = ["macros"] }

[features]
real-overseer = [ "indracore-service/real-overseer" ]
