[package]
name = "indracore-node-core-runtime-api"
version = "0.1.0"
authors = ["Selendra <nath@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
sp-api = { path = "../../../substrate/primitives/api" }
sp-core = { path = "../../../substrate/primitives/core" }

indracore-primitives = { path = "../../../primitives" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { path = "../../../substrate/primitives/core" }
futures = { version = "0.3.8", features = ["thread-pool"] }
indracore-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
